### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by ytaylordev** [Adalab/modulo-1-evaluacion-final-beafig#1]
Muy buen trabajo @beafig  !!!

Aquí tienes unos consejos para mejorar tu ejercicio:

- [x] HTML > ATRIBUTOS: Todos los `img` deben tener el atributo `title`: https://github.com/Adalab/modulo-1-evaluacion-final-beafig/blob/05ab9ec31596a5c00a806b35e61bdd33077e8428/src/html/partials/main.html#L13-L16 
- [x] HTML > MÓDULO 3 REASON: Debe haber un elemento con el texto "Cualquier Nivel": https://github.com/Adalab/modulo-1-evaluacion-final-beafig/blob/05ab9ec31596a5c00a806b35e61bdd33077e8428/src/html/partials/main.html#L47 

Ánimo y si tienes cualquier duda avísame!!!

> Con cada mejora que hagas, márcala como completada en este issue y su súbela a este repo.

> Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by beafig** [comment]
Hola Yanelis! 
Muchas gracias! Ya he resuelto los issues que me dices, pero no se como marcarlos como completados sin cerrar el issue! 🙃

**Comment by ytaylordev** [comment]
Buen trabajo @beafig, no me di cuenta que no me había activado los checks. 

Saludos
